# Generated by Django 2.2.2 on 2019-07-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20190723_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id_number',
            field=models.BigIntegerField(),
        ),
    ]
