# Generated by Django 2.2.1 on 2019-05-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20190528_1810'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_in_months',
            field=models.SmallIntegerField(),
        ),
    ]
